version: '2'
services:
  webmachine:
    build: ./web/src/MvcMovie
    ports:
     - "35000:5000"
    depends_on:
     - dbmachine
  dbmachine:
    build: ./db
    environment:
     - POSTGRES_DB=MvcMovie
     - POSTGRES_USER=naamunds
     - POSTGRES_PASSWORD=magicPassword
